import type { Category } from "@/lib/types"

export const categories: Category[] = [
  {
    id: "cat-sofa",
    slug: "sofa",
    name: "Sofa & Living",
    description: "Comfortable sofas, armchairs and ottomans for your living room",
    image: "/images/categories/sofa.jpg",
    icon: "sofa",
    productCount: 4,
    featured: true,
  },
  {
    id: "cat-mattress",
    slug: "mattress",
    name: "Mattress",
    description: "Quality mattresses for a restful night's sleep",
    image: "/images/categories/mattress.jpg",
    icon: "bed",
    productCount: 3,
    featured: true,
  },
  {
    id: "cat-bedroom",
    slug: "bedroom",
    name: "Bedroom",
    description: "Beds, wardrobes and bedroom furniture for a peaceful retreat",
    image: "/images/categories/bedroom.jpg",
    icon: "moon",
    productCount: 3,
    featured: true,
  },
  {
    id: "cat-dining",
    slug: "dining",
    name: "Dining",
    description: "Dining tables, chairs and sets for memorable family meals",
    image: "/images/categories/dining.jpg",
    icon: "utensils",
    productCount: 3,
    featured: true,
  },
  {
    id: "cat-living-room",
    slug: "living-room",
    name: "Living Room",
    description: "TV consoles, coffee tables and display shelves",
    image: "/images/categories/living-room.jpg",
    icon: "tv",
    productCount: 3,
    featured: true,
  },
  {
    id: "cat-office",
    slug: "office",
    name: "Office Furniture",
    description: "Work desks, ergonomic chairs and storage for home offices",
    image: "/images/categories/office.jpg",
    icon: "laptop",
    productCount: 3,
    featured: false,
  },
  {
    id: "cat-promotion",
    slug: "promotion",
    name: "Promotion",
    description: "Special deals and limited-time offers",
    image: "/images/categories/promotion.jpg",
    icon: "tag",
    productCount: 5,
    featured: true,
  },
]

export const subFilters = [
  { id: "ready-stock", label: "Ready Stock" },
  { id: "new-arrival", label: "New Arrival" },
  { id: "best-seller", label: "Best Seller" },
  { id: "premium", label: "Premium Collection" },
  { id: "value", label: "Value Package" },
] as const
