import type { Member } from "@/lib/types"

export const members: Member[] = [
  {
    id: "mem-001",
    quickInfo: {
      firstName: "Siti",
      lastName: "Rahimah",
      phone: "60123456789",
      email: "siti.rahimah@email.com",
      preferredLanguage: "bm",
    },
    profile: {
      birthday: "1985-03-12",
      gender: "female",
      addressLine1: "No. 12, Jalan Bahagia 3",
      addressLine2: "Taman Bahagia",
      city: "Shah Alam",
      postcode: "40150",
      state: "Selangor",
      householdSize: 4,
      purchasePurpose: "renovation",
      preferredStyles: ["scandinavian", "minimalist"],
      budget: "3000-5000",
      purchaseTimeline: "immediately",
      interestedCategories: ["sofa", "bedroom", "dining"],
    },
    discProfile: {
      type: "S",
      scores: { D: 15, I: 22, S: 45, C: 18 },
      communicationStyle: "Warm, patient and relationship-focused. Values harmony and reliability.",
      preferredApproach: "Share customer testimonials and emphasise after-sales support.",
      completedAt: "2026-01-08",
    },
    marketingConsent: true,
    createdAt: "2026-01-08",
    updatedAt: "2026-06-18",
    totalOrders: 2,
    totalSpend: 5948,
    wishlistIds: ["prod-003", "prod-009"],
  },
  {
    id: "mem-002",
    quickInfo: {
      firstName: "David",
      lastName: "Lim",
      phone: "60129876543",
      email: "david.lim@email.com",
      preferredLanguage: "en",
    },
    profile: {
      birthday: "1978-07-24",
      gender: "male",
      addressLine1: "Unit 8-12, Residensi Utama",
      addressLine2: "Jalan PJU 7/9",
      city: "Petaling Jaya",
      postcode: "47810",
      state: "Selangor",
      householdSize: 2,
      purchasePurpose: "new-home",
      preferredStyles: ["modern", "japandi"],
      budget: "5000-10000",
      purchaseTimeline: "1-month",
      interestedCategories: ["bedroom", "dining", "living-room"],
    },
    discProfile: {
      type: "D",
      scores: { D: 48, I: 18, S: 20, C: 14 },
      communicationStyle: "Direct, results-oriented, values efficiency.",
      preferredApproach: "Lead with key facts and benefits. Avoid lengthy explanations.",
      completedAt: "2026-06-20",
    },
    marketingConsent: false,
    createdAt: "2026-06-20",
    updatedAt: "2026-06-23",
    totalOrders: 2,
    totalSpend: 8947,
    wishlistIds: ["prod-006", "prod-015"],
  },
  {
    id: "mem-003",
    quickInfo: {
      firstName: "Jennifer",
      lastName: "Wong",
      phone: "60167654321",
      email: "jennifer.wong@email.com",
      preferredLanguage: "en",
    },
    profile: {
      birthday: "1990-11-05",
      gender: "female",
      addressLine1: "No. 5, Lorong Damai 2",
      city: "Cheras",
      postcode: "56000",
      state: "Kuala Lumpur",
      householdSize: 3,
      purchasePurpose: "renovation",
      preferredStyles: ["modern", "minimalist"],
      budget: "1000-3000",
      purchaseTimeline: "3-months",
      interestedCategories: ["office", "living-room", "bedroom"],
    },
    marketingConsent: false,
    createdAt: "2026-06-23",
    updatedAt: "2026-06-23",
    totalOrders: 1,
    totalSpend: 2398,
    wishlistIds: ["prod-001", "prod-014"],
  },
]
