import type { Order } from "@/lib/types"

export const orders: Order[] = [
  {
    id: "ord-001",
    orderNumber: "FNT-2026-00127",
    customerId: "mem-001",
    items: [
      {
        productId: "prod-001",
        productName: "Nordic L-Shape Sofa",
        productImage: "/api/placeholder?w=96&h=96&label=sofa-l-shape",
        sku: "FNT-SOF-001",
        quantity: 1,
        unitPrice: 3299,
        subtotal: 3299,
        installationRequested: true,
      },
    ],
    status: "completed",
    paymentMethod: "full-payment",
    paymentStatus: "paid",
    subtotal: 3299,
    deliveryFee: 0,
    installationFee: 150,
    discount: 0,
    total: 3449,
    amountPaid: 3449,
    balanceDue: 0,
    delivery: {
      recipientName: "Siti Rahimah",
      phone: "60123456789",
      addressLine1: "No. 12, Jalan Bahagia 3",
      addressLine2: "Taman Bahagia",
      city: "Shah Alam",
      postcode: "40150",
      state: "Selangor",
      scheduledDate: "2026-01-15",
      timeSlot: "9am â€“ 12pm",
    },
    estimatedDeliveryDate: "2026-01-15",
    actualDeliveryDate: "2026-01-15",
    createdAt: "2026-01-08",
    updatedAt: "2026-01-15",
  },
  {
    id: "ord-002",
    orderNumber: "FNT-2026-00198",
    customerId: "mem-001",
    items: [
      {
        productId: "prod-005",
        productName: "Harmony Pocketed Spring Mattress (King)",
        productImage: "/api/placeholder?w=96&h=96&label=mattress-spring",
        sku: "FNT-MAT-001",
        quantity: 1,
        unitPrice: 2499,
        subtotal: 2499,
        installationRequested: false,
      },
    ],
    status: "out-for-delivery",
    paymentMethod: "deposit",
    paymentStatus: "partial",
    subtotal: 2499,
    deliveryFee: 0,
    installationFee: 0,
    discount: 0,
    total: 2499,
    amountPaid: 500,
    balanceDue: 1999,
    delivery: {
      recipientName: "Siti Rahimah",
      phone: "60123456789",
      addressLine1: "No. 12, Jalan Bahagia 3",
      addressLine2: "Taman Bahagia",
      city: "Shah Alam",
      postcode: "40150",
      state: "Selangor",
      scheduledDate: "2026-06-25",
      timeSlot: "2pm â€“ 5pm",
    },
    estimatedDeliveryDate: "2026-06-25",
    createdAt: "2026-06-18",
    updatedAt: "2026-06-23",
  },
  {
    id: "ord-003",
    orderNumber: "FNT-2026-00215",
    customerId: "mem-002",
    items: [
      {
        productId: "prod-008",
        productName: "King Platform Bed Frame",
        productImage: "/api/placeholder?w=96&h=96&label=bed-king",
        sku: "FNT-BED-001",
        quantity: 1,
        unitPrice: 2899,
        subtotal: 2899,
        installationRequested: true,
      },
      {
        productId: "prod-010",
        productName: "Bedside Table Set (x2)",
        productImage: "/api/placeholder?w=96&h=96&label=bedside",
        sku: "FNT-BED-003",
        quantity: 1,
        unitPrice: 599,
        subtotal: 599,
        installationRequested: false,
      },
    ],
    status: "delivery-scheduled",
    paymentMethod: "full-payment",
    paymentStatus: "paid",
    subtotal: 3498,
    deliveryFee: 0,
    installationFee: 200,
    discount: 200,
    total: 3498,
    amountPaid: 3498,
    balanceDue: 0,
    delivery: {
      recipientName: "David Lim",
      phone: "60129876543",
      addressLine1: "Unit 8-12, Residensi Utama",
      addressLine2: "Jalan PJU 7/9",
      city: "Petaling Jaya",
      postcode: "47810",
      state: "Selangor",
      scheduledDate: "2026-06-28",
      timeSlot: "9am â€“ 12pm",
    },
    estimatedDeliveryDate: "2026-06-28",
    createdAt: "2026-06-20",
    updatedAt: "2026-06-23",
  },
  {
    id: "ord-004",
    orderNumber: "FNT-2026-00231",
    customerId: "mem-003",
    items: [
      {
        productId: "prod-017",
        productName: "Ergonomic Mesh Office Chair",
        productImage: "/api/placeholder?w=96&h=96&label=office-chair",
        sku: "FNT-OFF-001",
        quantity: 1,
        unitPrice: 1299,
        subtotal: 1299,
        installationRequested: false,
      },
      {
        productId: "prod-018",
        productName: "L-Shape Work Desk 140cm",
        productImage: "/api/placeholder?w=96&h=96&label=l-desk",
        sku: "FNT-OFF-002",
        quantity: 1,
        unitPrice: 999,
        subtotal: 999,
        installationRequested: true,
      },
    ],
    status: "confirming",
    paymentMethod: "in-store",
    paymentStatus: "pending",
    subtotal: 2298,
    deliveryFee: 0,
    installationFee: 100,
    discount: 0,
    total: 2398,
    amountPaid: 0,
    balanceDue: 2398,
    delivery: {
      recipientName: "Jennifer Wong",
      phone: "60167654321",
      addressLine1: "No. 5, Lorong Damai 2",
      city: "Cheras",
      postcode: "56000",
      state: "Kuala Lumpur",
    },
    estimatedDeliveryDate: "2026-07-05",
    createdAt: "2026-06-23",
    updatedAt: "2026-06-23",
  },
  {
    id: "ord-005",
    orderNumber: "FNT-2025-01847",
    customerId: "mem-002",
    items: [
      {
        productId: "prod-011",
        productName: "Solid Wood 6-Seater Dining Set",
        productImage: "/api/placeholder?w=96&h=96&label=dining-6seater",
        sku: "FNT-DIN-001",
        quantity: 1,
        unitPrice: 4299,
        subtotal: 4299,
        installationRequested: true,
      },
    ],
    status: "after-sales",
    paymentMethod: "full-payment",
    paymentStatus: "paid",
    subtotal: 4299,
    deliveryFee: 0,
    installationFee: 150,
    discount: 0,
    total: 4449,
    amountPaid: 4449,
    balanceDue: 0,
    delivery: {
      recipientName: "David Lim",
      phone: "60129876543",
      addressLine1: "Unit 8-12, Residensi Utama",
      addressLine2: "Jalan PJU 7/9",
      city: "Petaling Jaya",
      postcode: "47810",
      state: "Selangor",
      scheduledDate: "2025-12-10",
      timeSlot: "9am â€“ 12pm",
    },
    estimatedDeliveryDate: "2025-12-10",
    actualDeliveryDate: "2025-12-10",
    createdAt: "2025-12-01",
    updatedAt: "2026-06-10",
    notes: "Minor scratch reported on tabletop. After-sales team attending.",
  },
]
