import type { Product } from "@/lib/types"

export const products: Product[] = [
  // ── SOFA (4) ─────────────────────────────────────────────────────
  {
    id: "prod-001",
    slug: "nordic-l-shape-sofa-grey",
    name: "Nordic L-Shape Sofa",
    sku: "FNT-SOF-001",
    category: "sofa",
    brand: "Finotti Signature",
    price: 3299,
    originalPrice: 3999,
    images: [
      { url: "/images/products/sofa-l-shape/main.jpg", alt: "Nordic L-Shape Sofa in grey", isMain: true },
      { url: "/images/products/sofa-l-shape/02.jpg", alt: "Side view of L-Shape Sofa" },
      { url: "/images/products/sofa-l-shape/03.jpg", alt: "Close-up fabric detail" },
      { url: "/images/products/sofa-l-shape/04.jpg", alt: "Sofa in living room setting" },
    ],
    specs: {
      dimensions: "W280 x D160 x H85 cm",
      material: "Premium Fabric (Polyester)",
      color: "Light Grey",
      warranty: "2 Years",
      seatingCapacity: "5-6 persons",
      style: "scandinavian",
      deliveryDays: 7,
    },
    stock: "ready",
    tags: ["best-seller", "promotion"],
    rating: 4.8,
    reviewCount: 127,
    description:
      "The Nordic L-Shape Sofa combines clean Scandinavian lines with plush seating comfort. Ideal for families who enjoy spacious, relaxed living. The high-density foam cushions maintain their shape over years of use.",
    highlights: [
      "High-density foam cushions — stays firm for years",
      "Removable & washable cushion covers",
      "Anti-scratch legs in solid oak finish",
      "Fits in most standard Malaysian living rooms",
    ],
    careInstructions: "Vacuum regularly. Spot clean with mild detergent. Avoid direct sunlight.",
    suitableFor: "Families of 4–6 persons. Living rooms 15 sqm and above.",
    installationAvailable: true,
    installationFee: 150,
    showroomSample: true,
    relatedProductIds: ["prod-002", "prod-003", "prod-013"],
  },
  {
    id: "prod-002",
    slug: "recliner-armchair-cream",
    name: "Luxury Recliner Armchair",
    sku: "FNT-SOF-002",
    category: "sofa",
    brand: "Finotti Signature",
    price: 1899,
    images: [
      { url: "/images/products/recliner/main.jpg", alt: "Luxury Recliner Armchair in cream", isMain: true },
      { url: "/images/products/recliner/02.jpg", alt: "Reclined position" },
      { url: "/images/products/recliner/03.jpg", alt: "Detail of armrest" },
    ],
    specs: {
      dimensions: "W85 x D90 x H105 cm (reclined: D150 cm)",
      material: "Full-Grain Leather",
      color: "Cream / Ivory",
      warranty: "3 Years",
      seatingCapacity: "1 person",
      style: "classic",
      deliveryDays: 14,
    },
    stock: "low",
    tags: ["new-arrival", "premium"],
    rating: 4.9,
    reviewCount: 43,
    description:
      "Experience ultimate relaxation with this full-grain leather recliner. Perfect for reading corners, home theatres or simply unwinding after a long day.",
    highlights: [
      "Full-grain genuine leather — improves with age",
      "360° swivel base",
      "Smooth manual recline mechanism",
      "Built-in lumbar support",
    ],
    careInstructions: "Wipe with soft damp cloth. Condition leather every 6 months.",
    suitableFor: "Adults. Living rooms, bedrooms, reading nooks.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-001", "prod-003"],
  },
  {
    id: "prod-003",
    slug: "2-seater-sofa-velvet-teal",
    name: "Velvet 2-Seater Sofa",
    sku: "FNT-SOF-003",
    category: "sofa",
    brand: "Casa Living",
    price: 2199,
    originalPrice: 2599,
    images: [
      { url: "/images/products/sofa-2seater/main.jpg", alt: "Velvet 2-Seater Sofa in teal", isMain: true },
      { url: "/images/products/sofa-2seater/02.jpg", alt: "Overhead view" },
    ],
    specs: {
      dimensions: "W180 x D85 x H80 cm",
      material: "Velvet (Polyester)",
      color: "Deep Teal",
      warranty: "1 Year",
      seatingCapacity: "2 persons",
      style: "modern",
      deliveryDays: 10,
    },
    stock: "ready",
    tags: ["promotion", "hot"],
    rating: 4.6,
    reviewCount: 88,
    description:
      "A statement piece for compact living spaces. The rich velvet upholstery adds a touch of luxury while the slim legs keep the look light and airy.",
    highlights: [
      "Rich velvet texture — luxurious look and feel",
      "Slim tapered legs in gold finish",
      "Compact size — perfect for apartments",
      "Available in 4 colours (order in-store)",
    ],
    careInstructions: "Brush with soft velvet brush. Spot clean only.",
    suitableFor: "Couples and single adults. Condominiums and compact homes.",
    installationAvailable: false,
    showroomSample: false,
    relatedProductIds: ["prod-001", "prod-002"],
  },
  {
    id: "prod-004",
    slug: "ottoman-coffee-table-set",
    name: "Ottoman & Coffee Table Set",
    sku: "FNT-SOF-004",
    category: "sofa",
    brand: "Finotti Signature",
    price: 899,
    images: [
      { url: "/images/products/ottoman/main.jpg", alt: "Ottoman and coffee table set", isMain: true },
      { url: "/images/products/ottoman/02.jpg", alt: "Ottoman used as seat" },
    ],
    specs: {
      dimensions: "Ottoman: W60 x D60 x H45 cm | Table: W80 x D80 x H45 cm",
      material: "Linen blend & Solid Wood",
      color: "Warm Beige",
      warranty: "1 Year",
      style: "minimalist",
      deliveryDays: 7,
    },
    stock: "ready",
    tags: ["best-seller", "value"],
    rating: 4.5,
    reviewCount: 62,
    description:
      "A versatile set that serves as extra seating, a footrest or a coffee table. The storage ottoman hides away blankets and magazines.",
    highlights: [
      "2-in-1 ottoman with hidden storage",
      "Solid rubberwood legs",
      "Complements any sofa colour",
      "Easy self-assembly",
    ],
    careInstructions: "Wipe fabric with damp cloth. Polish wood with furniture wax monthly.",
    suitableFor: "All family types. Living rooms and reading areas.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-001", "prod-003"],
  },

  // ── MATTRESS (3) ─────────────────────────────────────────────────
  {
    id: "prod-005",
    slug: "harmony-pocketed-spring-mattress-king",
    name: "Harmony Pocketed Spring Mattress (King)",
    sku: "FNT-MAT-001",
    category: "mattress",
    brand: "SleepWell",
    price: 2499,
    originalPrice: 2999,
    images: [
      { url: "/images/products/mattress-spring/main.jpg", alt: "Pocketed Spring Mattress King size", isMain: true },
      { url: "/images/products/mattress-spring/02.jpg", alt: "Mattress cross-section layers" },
      { url: "/images/products/mattress-spring/03.jpg", alt: "Mattress in bedroom setting" },
    ],
    specs: {
      dimensions: "W183 x L190 x H28 cm (King)",
      material: "Pocketed Spring + Memory Foam + Bamboo Cover",
      color: "White / Cream",
      warranty: "10 Years",
      style: "modern",
      deliveryDays: 7,
    },
    stock: "ready",
    tags: ["best-seller", "hot"],
    rating: 4.9,
    reviewCount: 215,
    description:
      "2000 individually pocketed springs eliminate motion transfer — perfect for couples. Three layers of foam ensure pressure-point relief from head to toe.",
    highlights: [
      "2000 pocketed springs — zero motion transfer",
      "Cooling bamboo charcoal cover",
      "Flippable for extended lifespan",
      "Certified by SIRIM",
    ],
    careInstructions: "Rotate 180° every 3 months. Use mattress protector. Spot clean only.",
    suitableFor: "Couples. All sleeping positions.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-008", "prod-009"],
  },
  {
    id: "prod-006",
    slug: "natural-latex-mattress-queen",
    name: "Natural Latex Mattress (Queen)",
    sku: "FNT-MAT-002",
    category: "mattress",
    brand: "EcoRest",
    price: 3199,
    images: [
      { url: "/images/products/mattress-latex/main.jpg", alt: "Natural Latex Mattress Queen size", isMain: true },
      { url: "/images/products/mattress-latex/02.jpg", alt: "Latex layer detail" },
    ],
    specs: {
      dimensions: "W152 x L190 x H20 cm (Queen)",
      material: "100% Natural Latex + Organic Cotton Cover",
      color: "White",
      warranty: "15 Years",
      style: "minimalist",
      deliveryDays: 14,
    },
    stock: "pre-order",
    tags: ["premium", "new-arrival"],
    rating: 4.7,
    reviewCount: 56,
    description:
      "Sustainably harvested natural latex provides responsive support that molds to your body shape. Naturally hypoallergenic and breathable for Malaysia's climate.",
    highlights: [
      "100% certified natural latex (Rainforest Alliance)",
      "Hypoallergenic — ideal for allergy sufferers",
      "Breathable open-cell structure",
      "15-year warranty — long-term investment",
    ],
    careInstructions: "Never fold. Air out every 6 months. Use breathable mattress protector.",
    suitableFor: "Allergy sufferers. Side and back sleepers.",
    installationAvailable: false,
    showroomSample: false,
    relatedProductIds: ["prod-005"],
  },
  {
    id: "prod-007",
    slug: "kids-single-foam-mattress",
    name: "Kids Single Foam Mattress",
    sku: "FNT-MAT-003",
    category: "mattress",
    brand: "SleepWell",
    price: 699,
    originalPrice: 899,
    images: [
      { url: "/images/products/mattress-kids/main.jpg", alt: "Kids single foam mattress", isMain: true },
    ],
    specs: {
      dimensions: "W91 x L190 x H15 cm (Single)",
      material: "High-Density Foam + Waterproof Cover",
      color: "White / Blue",
      warranty: "5 Years",
      style: "modern",
      deliveryDays: 5,
    },
    stock: "ready",
    tags: ["value", "promotion"],
    rating: 4.5,
    reviewCount: 94,
    description:
      "Firm support for growing children. The waterproof cover protects against accidents while the breathable foam keeps children cool through the night.",
    highlights: [
      "Child-safe high-density foam (no off-gassing)",
      "Washable waterproof cover",
      "Edge-to-edge support",
      "Ready stock — fast delivery",
    ],
    careInstructions: "Remove and wash cover monthly. Spot clean foam with mild soap.",
    suitableFor: "Children aged 3 and above. Single beds.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-005"],
  },

  // ── BEDROOM (3) ──────────────────────────────────────────────────
  {
    id: "prod-008",
    slug: "king-platform-bed-walnut",
    name: "King Platform Bed Frame",
    sku: "FNT-BED-001",
    category: "bedroom",
    brand: "Finotti Signature",
    price: 2899,
    originalPrice: 3299,
    images: [
      { url: "/images/products/bed-king/main.jpg", alt: "King Platform Bed Frame in walnut", isMain: true },
      { url: "/images/products/bed-king/02.jpg", alt: "Bed headboard detail" },
      { url: "/images/products/bed-king/03.jpg", alt: "Bed with mattress in room" },
    ],
    specs: {
      dimensions: "W193 x L208 x H110 cm (fits King 183cm mattress)",
      material: "Solid Walnut Wood + MDF",
      color: "Walnut Brown",
      warranty: "5 Years",
      style: "japandi",
      deliveryDays: 14,
    },
    stock: "ready",
    tags: ["best-seller", "premium"],
    rating: 4.8,
    reviewCount: 74,
    description:
      "A statement piece that anchors your bedroom with understated elegance. The solid walnut headboard and low-profile frame create a calming Japandi aesthetic.",
    highlights: [
      "Solid walnut headboard — luxurious warmth",
      "Under-bed storage space (30cm clearance)",
      "Reinforced center beam — supports up to 500kg",
      "Compatible with all standard King mattresses",
    ],
    careInstructions: "Polish with furniture wax monthly. Avoid direct sunlight.",
    suitableFor: "Adults. Master bedroom. Minimalist and luxury décor styles.",
    installationAvailable: true,
    installationFee: 200,
    showroomSample: true,
    relatedProductIds: ["prod-005", "prod-009"],
    bundleProductIds: ["prod-005"],
  },
  {
    id: "prod-009",
    slug: "6-door-wardrobe-white-oak",
    name: "6-Door Sliding Wardrobe",
    sku: "FNT-BED-002",
    category: "bedroom",
    brand: "Casa Living",
    price: 3499,
    images: [
      { url: "/images/products/wardrobe/main.jpg", alt: "6-Door Sliding Wardrobe in white oak", isMain: true },
      { url: "/images/products/wardrobe/02.jpg", alt: "Interior storage compartments" },
      { url: "/images/products/wardrobe/03.jpg", alt: "Wardrobe in bedroom" },
    ],
    specs: {
      dimensions: "W240 x D60 x H210 cm",
      material: "Melamine Board + Aluminium Frame",
      color: "White Oak",
      warranty: "3 Years",
      style: "modern",
      deliveryDays: 21,
    },
    stock: "pre-order",
    tags: ["premium", "new-arrival"],
    rating: 4.6,
    reviewCount: 31,
    description:
      "Maximise your bedroom storage without compromising on style. The 6-panel sliding doors eliminate the need for door clearance space — ideal for smaller rooms.",
    highlights: [
      "Smooth Japanese sliding track system",
      "Adjustable shelves and hanging rails",
      "Mirror panel option available (in-store)",
      "Soft-close mechanism on all drawers",
    ],
    careInstructions: "Wipe with dry cloth. Clean tracks monthly to ensure smooth sliding.",
    suitableFor: "Adults. Bedrooms with limited floor space.",
    installationAvailable: true,
    installationFee: 300,
    showroomSample: false,
    relatedProductIds: ["prod-008"],
  },
  {
    id: "prod-010",
    slug: "bedside-table-set-of-2",
    name: "Bedside Table Set (x2)",
    sku: "FNT-BED-003",
    category: "bedroom",
    brand: "Finotti Signature",
    price: 599,
    originalPrice: 799,
    images: [
      { url: "/images/products/bedside/main.jpg", alt: "Bedside table set of 2", isMain: true },
      { url: "/images/products/bedside/02.jpg", alt: "Bedside table with lamp" },
    ],
    specs: {
      dimensions: "W50 x D40 x H55 cm (each)",
      material: "Rubberwood + MDF",
      color: "Natural Oak",
      warranty: "1 Year",
      style: "scandinavian",
      deliveryDays: 5,
    },
    stock: "ready",
    tags: ["best-seller", "value"],
    rating: 4.7,
    reviewCount: 189,
    description:
      "A matching pair of bedside tables with a drawer and open shelf. The natural oak finish pairs beautifully with both light and dark bedroom colour schemes.",
    highlights: [
      "Set of 2 — great value",
      "Soft-close drawer",
      "Open shelf for books and devices",
      "Ready stock — delivered within a week",
    ],
    careInstructions: "Wipe with soft damp cloth. Avoid harsh chemicals.",
    suitableFor: "All bedroom types. Pairs with most bed frames.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-008"],
  },

  // ── DINING (3) ───────────────────────────────────────────────────
  {
    id: "prod-011",
    slug: "solid-wood-6-seater-dining-set",
    name: "Solid Wood 6-Seater Dining Set",
    sku: "FNT-DIN-001",
    category: "dining",
    brand: "Finotti Signature",
    price: 4299,
    originalPrice: 4999,
    images: [
      { url: "/images/products/dining-6seater/main.jpg", alt: "6-Seater Solid Wood Dining Set", isMain: true },
      { url: "/images/products/dining-6seater/02.jpg", alt: "Table surface detail" },
      { url: "/images/products/dining-6seater/03.jpg", alt: "Full dining set in room" },
    ],
    specs: {
      dimensions: "Table: W180 x D90 x H76 cm | Chair: W46 x D52 x H90 cm",
      material: "Solid Teak Wood",
      color: "Natural Teak",
      warranty: "5 Years",
      seatingCapacity: "6 persons",
      style: "classic",
      deliveryDays: 21,
    },
    stock: "pre-order",
    tags: ["premium", "best-seller"],
    rating: 4.9,
    reviewCount: 45,
    description:
      "Heirloom-quality solid teak dining furniture built to last generations. The natural grain patterns make each piece uniquely beautiful.",
    highlights: [
      "100% solid teak — not veneer",
      "Mortise and tenon joinery — no screws",
      "Naturally water and heat resistant",
      "Extendable table option (+60cm, order separately)",
    ],
    careInstructions: "Oil with teak oil every 6 months. Wipe spills immediately.",
    suitableFor: "Families of 4–6. Formal and casual dining rooms.",
    installationAvailable: true,
    installationFee: 150,
    showroomSample: true,
    relatedProductIds: ["prod-012", "prod-013"],
  },
  {
    id: "prod-012",
    slug: "marble-top-4-seater-dining-table",
    name: "Marble Top Dining Table (4-Seater)",
    sku: "FNT-DIN-002",
    category: "dining",
    brand: "Casa Living",
    price: 2799,
    images: [
      { url: "/images/products/dining-marble/main.jpg", alt: "Marble Top Dining Table", isMain: true },
      { url: "/images/products/dining-marble/02.jpg", alt: "Marble surface close-up" },
    ],
    specs: {
      dimensions: "W140 x D80 x H75 cm",
      material: "Sintered Stone Top + Solid Steel Base",
      color: "Carrara White / Black",
      warranty: "2 Years",
      seatingCapacity: "4 persons",
      style: "modern",
      deliveryDays: 14,
    },
    stock: "ready",
    tags: ["hot", "premium"],
    rating: 4.7,
    reviewCount: 67,
    description:
      "Premium sintered stone surface that mimics Carrara marble — more durable and scratch-resistant than natural stone. The matte black steel base adds industrial edge.",
    highlights: [
      "Sintered stone — heat, scratch and stain resistant",
      "Adjustable levelling feet",
      "Maintenance-free surface",
      "Suitable for indoor and covered outdoor use",
    ],
    careInstructions: "Wipe clean with any household cleaner. Stone surface is fully sealed.",
    suitableFor: "Modern and contemporary homes. Families of 2–4.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-011"],
  },
  {
    id: "prod-013",
    slug: "bar-stool-counter-height-set-2",
    name: "Counter Height Bar Stools (Set of 2)",
    sku: "FNT-DIN-003",
    category: "dining",
    brand: "Casa Living",
    price: 699,
    originalPrice: 899,
    images: [
      { url: "/images/products/bar-stools/main.jpg", alt: "Counter Height Bar Stools set of 2", isMain: true },
      { url: "/images/products/bar-stools/02.jpg", alt: "Bar stools at kitchen island" },
    ],
    specs: {
      dimensions: "W42 x D40 x H65–85 cm (adjustable)",
      material: "Genuine Leather Seat + Stainless Steel",
      color: "Black / Chrome",
      warranty: "1 Year",
      seatingCapacity: "2 persons",
      style: "industrial",
      deliveryDays: 7,
    },
    stock: "ready",
    tags: ["promotion", "value"],
    rating: 4.5,
    reviewCount: 112,
    description:
      "Height-adjustable bar stools with a 360° swivel seat. Perfect for kitchen islands, breakfast bars and open-concept dining areas.",
    highlights: [
      "Adjustable height: 65–85 cm",
      "360° swivel",
      "Non-scratch rubber feet",
      "Set of 2 — ready to use",
    ],
    careInstructions: "Wipe leather with damp cloth. Polish steel with dry microfibre cloth.",
    suitableFor: "Adults. Kitchen islands, home bars, open-plan kitchens.",
    installationAvailable: false,
    showroomSample: false,
    relatedProductIds: ["prod-012"],
  },

  // ── LIVING ROOM (3) ──────────────────────────────────────────────
  {
    id: "prod-014",
    slug: "tv-console-180cm-walnut",
    name: "TV Console 180cm with Storage",
    sku: "FNT-LIV-001",
    category: "living-room",
    brand: "Finotti Signature",
    price: 1499,
    originalPrice: 1799,
    images: [
      { url: "/images/products/tv-console/main.jpg", alt: "TV Console 180cm Walnut", isMain: true },
      { url: "/images/products/tv-console/02.jpg", alt: "Console with TV mounted" },
      { url: "/images/products/tv-console/03.jpg", alt: "Storage compartments detail" },
    ],
    specs: {
      dimensions: "W180 x D45 x H55 cm",
      material: "Solid Rubberwood + Walnut Veneer",
      color: "Walnut / Natural",
      warranty: "2 Years",
      style: "japandi",
      deliveryDays: 10,
    },
    stock: "ready",
    tags: ["best-seller", "hot"],
    rating: 4.8,
    reviewCount: 156,
    description:
      "A sleek TV console with generous storage. Three covered cabinets hide cable clutter while the open shelf keeps your media devices accessible.",
    highlights: [
      "Cable management ports at back",
      "Soft-close cabinet doors",
      "Supports TVs up to 75 inches",
      "Multiple finish options available in-store",
    ],
    careInstructions: "Wipe with dry cloth. Condition veneer surface every 6 months.",
    suitableFor: "All family types. TVs 55–75 inches.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-001", "prod-015"],
  },
  {
    id: "prod-015",
    slug: "coffee-table-round-glass-top",
    name: "Round Glass Top Coffee Table",
    sku: "FNT-LIV-002",
    category: "living-room",
    brand: "Casa Living",
    price: 899,
    images: [
      { url: "/images/products/coffee-table/main.jpg", alt: "Round Glass Top Coffee Table", isMain: true },
      { url: "/images/products/coffee-table/02.jpg", alt: "Table styled with accessories" },
    ],
    specs: {
      dimensions: "Ø90 x H45 cm",
      material: "10mm Tempered Glass + Solid Brass Frame",
      color: "Clear Glass / Gold",
      warranty: "1 Year",
      style: "luxury",
      deliveryDays: 7,
    },
    stock: "ready",
    tags: ["hot", "premium"],
    rating: 4.6,
    reviewCount: 78,
    description:
      "An open, airy centrepiece for your living room. The round shape improves traffic flow and the tempered glass top is safe for families with young children.",
    highlights: [
      "10mm tempered safety glass",
      "Solid brass frame — no rust",
      "Round edge — child-safe design",
      "Easy to clean glass surface",
    ],
    careInstructions: "Wipe glass with glass cleaner. Polish brass with dry cloth.",
    suitableFor: "Modern and luxury living rooms. Families with children.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-001", "prod-014"],
  },
  {
    id: "prod-016",
    slug: "display-shelf-5-tier",
    name: "5-Tier Display Shelf",
    sku: "FNT-LIV-003",
    category: "living-room",
    brand: "Casa Living",
    price: 499,
    originalPrice: 649,
    images: [
      { url: "/images/products/display-shelf/main.jpg", alt: "5-Tier Display Shelf", isMain: true },
      { url: "/images/products/display-shelf/02.jpg", alt: "Shelf styled with plants and books" },
    ],
    specs: {
      dimensions: "W80 x D25 x H175 cm",
      material: "Rubberwood + Iron",
      color: "Natural Oak / Black",
      warranty: "1 Year",
      style: "industrial",
      deliveryDays: 5,
    },
    stock: "ready",
    tags: ["value", "promotion"],
    rating: 4.4,
    reviewCount: 203,
    description:
      "A versatile shelving unit that works as a room divider, bookshelf or display for plants and collectibles. Easy to assemble in under 30 minutes.",
    highlights: [
      "Easy self-assembly — no tools required",
      "Anti-tip wall anchor included",
      "Each shelf holds up to 20kg",
      "Works as room divider in open-plan homes",
    ],
    careInstructions: "Wipe with soft damp cloth. Avoid placing in humid areas.",
    suitableFor: "All home types. Living rooms, home offices, bedrooms.",
    installationAvailable: false,
    showroomSample: false,
    relatedProductIds: ["prod-014"],
  },

  // ── OFFICE (3) ───────────────────────────────────────────────────
  {
    id: "prod-017",
    slug: "ergonomic-mesh-office-chair",
    name: "Ergonomic Mesh Office Chair",
    sku: "FNT-OFF-001",
    category: "office",
    brand: "WorkRight",
    price: 1299,
    originalPrice: 1599,
    images: [
      { url: "/images/products/office-chair/main.jpg", alt: "Ergonomic Mesh Office Chair", isMain: true },
      { url: "/images/products/office-chair/02.jpg", alt: "Lumbar support detail" },
      { url: "/images/products/office-chair/03.jpg", alt: "Chair adjustment controls" },
    ],
    specs: {
      dimensions: "W68 x D65 x H95–105 cm",
      material: "Mesh Back + PU Foam Seat",
      color: "Black / Grey",
      warranty: "3 Years",
      style: "modern",
      deliveryDays: 7,
    },
    stock: "ready",
    tags: ["best-seller", "hot"],
    rating: 4.7,
    reviewCount: 341,
    description:
      "Designed for 8-hour workdays. The breathable mesh back prevents heat build-up while the 12-point adjustability system accommodates all body types.",
    highlights: [
      "12-point adjustability — height, armrest, lumbar, tilt",
      "Breathable 3D mesh — stays cool in Malaysian heat",
      "Certified for 8 hours of continuous use",
      "Weight capacity: 130kg",
    ],
    careInstructions: "Vacuum mesh monthly. Wipe seat with mild damp cloth.",
    suitableFor: "Office workers. Work-from-home setup. All body types up to 130kg.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-018", "prod-019"],
  },
  {
    id: "prod-018",
    slug: "l-shape-work-desk-140cm",
    name: "L-Shape Work Desk 140cm",
    sku: "FNT-OFF-002",
    category: "office",
    brand: "WorkRight",
    price: 999,
    images: [
      { url: "/images/products/l-desk/main.jpg", alt: "L-Shape Work Desk", isMain: true },
      { url: "/images/products/l-desk/02.jpg", alt: "Desk with monitor setup" },
    ],
    specs: {
      dimensions: "W140 x D140 x H75 cm",
      material: "MDF Top + Steel Legs",
      color: "White / Grey / Oak (select in-store)",
      warranty: "2 Years",
      style: "modern",
      deliveryDays: 10,
    },
    stock: "ready",
    tags: ["value", "best-seller"],
    rating: 4.6,
    reviewCount: 127,
    description:
      "More workspace, less clutter. The L-shape design provides dedicated space for your monitor, laptop and stationery without the desk feeling crowded.",
    highlights: [
      "Dual monitor ready — wide surface",
      "Built-in cable management tray",
      "Sturdy steel legs with levelling feet",
      "Available in 3 colours",
    ],
    careInstructions: "Wipe with damp cloth. Avoid placing heavy items on edges.",
    suitableFor: "Work-from-home professionals. Students. Corner office setups.",
    installationAvailable: true,
    installationFee: 100,
    showroomSample: false,
    relatedProductIds: ["prod-017", "prod-019"],
  },
  {
    id: "prod-019",
    slug: "bookshelf-unit-5-shelf-white",
    name: "5-Shelf Bookshelf Unit",
    sku: "FNT-OFF-003",
    category: "office",
    brand: "Casa Living",
    price: 599,
    originalPrice: 749,
    images: [
      { url: "/images/products/bookshelf/main.jpg", alt: "5-Shelf Bookshelf Unit White", isMain: true },
      { url: "/images/products/bookshelf/02.jpg", alt: "Shelf with books and decor" },
    ],
    specs: {
      dimensions: "W80 x D30 x H185 cm",
      material: "Engineered Wood",
      color: "White",
      warranty: "1 Year",
      style: "minimalist",
      deliveryDays: 5,
    },
    stock: "ready",
    tags: ["value", "promotion"],
    rating: 4.4,
    reviewCount: 89,
    description:
      "A clean, functional bookshelf for home offices, children's rooms and living spaces. The adjustable shelves accommodate books, binders and office supplies of all sizes.",
    highlights: [
      "Adjustable shelf heights",
      "Anti-tip wall bracket included",
      "Easy assembly — approx. 45 minutes",
      "Each shelf: max 15kg",
    ],
    careInstructions: "Wipe with soft dry cloth. Avoid moisture.",
    suitableFor: "Home offices, study rooms, children's rooms.",
    installationAvailable: false,
    showroomSample: false,
    relatedProductIds: ["prod-017", "prod-018"],
  },

  // ── STORAGE (3) ──────────────────────────────────────────────────
  {
    id: "prod-020",
    slug: "shoe-cabinet-12-pairs",
    name: "Shoe Cabinet (12 Pairs)",
    sku: "FNT-STG-001",
    category: "living-room",
    brand: "Casa Living",
    price: 449,
    originalPrice: 549,
    images: [
      { url: "/images/products/shoe-cabinet/main.jpg", alt: "Shoe Cabinet 12 pairs capacity", isMain: true },
      { url: "/images/products/shoe-cabinet/02.jpg", alt: "Open cabinet showing shoe storage" },
    ],
    specs: {
      dimensions: "W80 x D35 x H110 cm",
      material: "Engineered Wood",
      color: "White / Oak",
      warranty: "1 Year",
      style: "minimalist",
      deliveryDays: 5,
    },
    stock: "ready",
    tags: ["best-seller", "value"],
    rating: 4.5,
    reviewCount: 267,
    description:
      "Keep your entrance clean and organised. The flip-open doors reveal tilted shoe racks that hold up to 12 pairs. The top surface doubles as a display or foyer console.",
    highlights: [
      "Holds 12 pairs — suitable for family of 4",
      "Flip-up doors — no door clearance needed",
      "Ventilation slots keep shoes fresh",
      "Flat top — use as a mini console",
    ],
    careInstructions: "Wipe with damp cloth. Do not use abrasive cleaners.",
    suitableFor: "Foyers and entrance areas. Families of 4.",
    installationAvailable: false,
    showroomSample: true,
    relatedProductIds: ["prod-016"],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts(tag: string, limit = 4): Product[] {
  return products.filter((p) => p.tags.includes(tag as any)).slice(0, limit)
}

export function getPromotionProducts(): Product[] {
  return products.filter(
    (p) => p.tags.includes("promotion") || (p.originalPrice && p.originalPrice > p.price)
  )
}
